[project]
name = "plat"
version = "0.0.1"
description = "Python Lagrangian Atmospheric Trajectory model"
requires-python = ">=3.8"
dependencies = [
    "xarray[complete]",
    "dask",
    "numpy",
    "numba",
]

[project.optional-dependencies]
plotting = [
    "matplotlib",
    "cartopy",
]
test = [
    "pytest",
    "plat[plotting]",
]
dev = [
    "ruff",
]
